# Generated by Django 2.0 on 2021-02-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialists',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialists',
            name='car',
            field=models.CharField(max_length=1),
        ),
    ]
